FROM ubuntu:xenial AS base
RUN apt-get update &&\
    apt-get -y \
        install build-essential docker.io \
        diffstat texinfo gawk chrpath wget cpio \
        language-pack-en \
        python \
        cmake
        
FROM base AS builder-poky-sumo
USER root
COPY deploy/build/tmp/deploy/sdk/poky-glibc-x86_64-meta-toolchain-aarch64-toolchain-2.5.1.sh /tmp
RUN bash /tmp/poky-glibc-x86_64-meta-toolchain-aarch64-toolchain-2.5.1.sh -y

FROM base as sdk-armv8
COPY --from=builder-poky-sumo /opt/poky /opt/poky
COPY repository/builder/armv8/init.sh /init.sh
WORKDIR /W
ENTRYPOINT ["/init.sh"]

CMD ["/bin/bash"]
