version: '2.3'
services:
  shim-mock:
    user: "${UID}:${GID}"
    container_name: shoortit
    build:
      context: ../mocking
    volumes:
      - $PWD:/oort
    working_dir: /oort/server
    restart: on-failure
    network_mode: host
    command: python3 tests/utils/test_shim.py 2

  bouncy:
    user: "0:0"
    container_name: bounceit
    privileged: true
    build:
      context: ../mocking
    volumes:
      - $PWD:/oort
    working_dir: /oort
    network_mode: host
    command: server/tests/utils/canbounce.sh

  oort-agent:
    user: "${UID}:${GID}"
    container_name: oortit
    build:
      context: ../mocking
    volumes:
      - $PWD:/oort
      - type: tmpfs
        target: /tmp/workdir.1
    working_dir: /oort
    network_mode: host
    # ports: [2005]
    depends_on: [shim-mock, bouncy]
    command: build/oort-server -w /tmp/workdir.1 -l debug -c can0 -n 12 -N 51

  shim-unit:
    user: "${UID}:${GID}"
    container_name: shunit
    build:
      context: ../mocking
    volumes:
      - $PWD:/oort
    working_dir: /oort/server
    network_mode: host
    command: python3 tests/utils/unit_shim.py 2

  unittest:
    user: "${UID}:${GID}"
    container_name: oortunit
    build:
      context: ../mocking
    volumes:
      - $PWD:/oort
    working_dir: /oort
    network_mode: host
    ports: [2005]
    depends_on: [shim-unit]
    environment: 
      - TESTS=""
      - LD_LIBRARY_PATH=/oort/build/external/lib
    command: sh -c "sleep 1 && build/server/test_agent ${TESTS}"
