version: '2.3'
services:
  oort-agent:
    user: "${UID}:${GID}"
    container_name: oortit
    build:
      context: ../mocking
    volumes:
      - $PWD:/oort
    working_dir: /oort
    network_mode: host
    ports: [2005]
    command: build/oort-server -w /tmp/workdir.1 -l debug -c can0 -n 12 -N 51

  shim-mock:
    user: "${UID}:${GID}"
    container_name: shoortit
    build:
      context: ../mocking
    volumes:
      - $PWD:/oort
    working_dir: /oort/server
    network_mode: host
    command: python3 tests/utils/test_shim.py
